version: "3"

services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
  web:
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - "8001:5000"
    depends_on:
      - db

  queue:
    build: .
    command: python consumer.py
